development:
  adapter: postgresql
  encoding: unicode
  database: restaurantly_dev
  pool: 5
  host: localhost
  port: 5432
  user: postgres
  password: nothing

test:
  adapter: postgresql
  encoding: unicode
  database: restaurantly_test
  pool: 5
  host: localhost
  port: 5432
  user: postgres
  password: nothing